package me.lazerka.mf.entity;

import com.googlecode.objectify.annotation.Index;
import com.googlecode.objectify.annotation.Unindex;
import org.joda.time.DateTime;
import org.joda.time.Minutes;

/**
 * @author Dzmitry Lazerka
 *
 * Not a class, but name "Channel" is used for allocating IDs in {@link me.lazerka.mf.rest.ChannelResource}.
 *
 */
public class Channel {
	public static final int DURATION_MINUTES = 120;

	/** Unique, generated by allocateId(). */
	@Index String clientId;

	@Index DateTime createdDate;

	@Unindex String token;

	private Channel() {
	}

	public Channel(String clientId, String token, DateTime createdDate) {
		this.clientId = clientId;
		this.token = token;
		this.createdDate = createdDate;
	}

	public boolean isExpired(DateTime now) {
		return Minutes.minutesBetween(createdDate, now).getMinutes() > DURATION_MINUTES;
	}

	public String getClientId() {
		return clientId;
	}

	public String getToken() {
		return token;
	}

	@Override
	public String toString() {
		return "Channel{" +
				"clientId='" + clientId + '\'' +
				", createdDate=" + createdDate +
				", token='" + token + '\'' +
				'}';
	}
}
