package me.lazerka.mf.gae.entity;

import org.joda.time.DateTime;

import javax.annotation.Nonnull;

import java.util.Objects;

import static com.google.common.base.Preconditions.checkNotNull;

/**
 * That's generated by GCM.
 *
 * @author Dzmitry Lazerka
 */
public class GcmRegistrationEntity {
	private String id;

	private DateTime createdDate;

	private int appVersion;

	private GcmRegistrationEntity() {}

	public GcmRegistrationEntity(
			@Nonnull String id,
			@Nonnull DateTime createdDate
	) {
		this.id = checkNotNull(id);
		this.createdDate = createdDate;
	}

	/** Long string, aka id. */
	public String getId() {
		return id;
	}

	public DateTime getCreatedDate() {
		return createdDate;
	}

	public void setAppVersion(int appVersion) {
		this.appVersion = appVersion;
	}

	public int getAppVersion() {
		return appVersion;
	}

	@Override
	public boolean equals(Object o) {
		if (this == o) return true;
		if (o == null || getClass() != o.getClass()) return false;
		GcmRegistrationEntity that = (GcmRegistrationEntity) o;
		return Objects.equals(id, that.id);
	}

	@Override
	public int hashCode() {
		return Objects.hash(id);
	}
}
