/*
 *     Find Us: privacy oriented location tracker for your friends and family.
 *     Copyright (C) 2015 Dzmitry Lazerka dlazerka@gmail.com
 *
 *     This program is free software; you can redistribute it and/or modify
 *     it under the terms of the GNU General Public License as published by
 *     the Free Software Foundation; either version 2 of the License, or
 *     (at your option) any later version.
 *
 *     This program is distributed in the hope that it will be useful,
 *     but WITHOUT ANY WARRANTY; without even the implied warranty of
 *     MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *     GNU General Public License for more details.
 *
 *     You should have received a copy of the GNU General Public License along
 *     with this program; if not, write to the Free Software Foundation, Inc.,
 *     51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
 *
 */

package me.lazerka.mf.gae.entity;

import com.googlecode.objectify.Ref;
import com.googlecode.objectify.annotation.Cache;
import com.googlecode.objectify.annotation.Entity;
import com.googlecode.objectify.annotation.Id;
import com.googlecode.objectify.annotation.Parent;
import me.lazerka.mf.gae.user.MfUser;
import org.joda.time.DateTime;

import javax.annotation.Nonnull;
import javax.annotation.Nullable;

import static com.google.common.base.Preconditions.checkNotNull;

/**
 * That's generated by GCM.
 *
 * @author Dzmitry Lazerka
 */
@Entity
@Cache
public class GcmRegistrationEntity {
	@Parent
	private Ref<MfUser> user;

	@Id
	private String id;

	private DateTime createdDate;

	@Nullable
	private Integer appVersion;

	private GcmRegistrationEntity() {}

	public GcmRegistrationEntity(
			@Nonnull MfUser user,
			@Nonnull String id,
			@Nonnull DateTime createdDate,
			@Nullable Integer appVersion
	) {
		this.user = Ref.create(user);
		this.id = checkNotNull(id);
		this.createdDate = checkNotNull(createdDate);
		this.appVersion = appVersion;
	}

	public GcmRegistrationEntity(@Nonnull MfUser user, String id, DateTime createdDate) {
		this(user, id, createdDate, null);
	}

	public Ref<MfUser> getUser() {
		return user;
	}

	/** Long string, aka id. */
	public String getId() {
		return id;
	}

	public DateTime getCreatedDate() {
		return createdDate;
	}

	public void setAppVersion(int appVersion) {
		this.appVersion = appVersion;
	}

	@Nullable
	public Integer getAppVersion() {
		return appVersion;
	}
}
